export const LOCATION_REQ = "LOCATION_REQ";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAILURE = "LOCATION_FAILURE";
export const LOCATION_DATA = "LOCATION_DATA";

export const GET_CITY_WEATHER_REQ = "GET_CITY_WEATHER_REQ";
export const  GET_CITY_WEATHER_SUCCESS = " GET_CITY_WEATHER_SUCCESS";
export const  GET_CITY_WEATHER_FAILURE = " GET_CITY_WEATHER_FAILURE";

export const GET_DAILY_WEATHER_REQ = "GET_DAILY_WEATHER_REQ";
export const GET_DAILY_WEATHER_SUCCESS = " GET_DAILY_WEATHER_SUCCESS";
export const GET_DAILY_WEATHER_FAILURE = " GET_DAILY_WEATHER_FAILURE";