export const LOCATION_REQ = "LOCATION_REQ";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";
export const LOCATION_FAILURE = "LOCATION_FAILURE";
export const LOCATION_DATA = "LOCATION_DATA";

export const GET_WEATHER_REQ = "LOCATION_REQ";
export const GET_WEATHER_SUCCESS = "GET_WEATHER_SUCCESS";
export const GET_WEATHER_FAILURE = "GET_WEATHER_FAILURE";

